# Generated by Django 5.0.3 on 2024-03-20 06:45

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFirst', models.CharField(max_length=120, null=True)),
                ('nameMiddle', models.CharField(blank=True, max_length=120, null=True)),
                ('nameLast', models.CharField(max_length=120, null=True)),
                ('birthdate', models.DateField(default=datetime.date.today)),
                ('age', models.PositiveIntegerField(blank=True, default=0, editable=False)),
                ('sex', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=6)),
                ('civilStatus', models.CharField(choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED'), ('WIDOWED', 'WIDOWED'), ('SEPARATED', 'SEPARATED')], default='SINGLE', max_length=9)),
                ('hospitalNumber', models.CharField(blank=True, default='', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', message='Format: 123456')])),
                ('contact', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,11}$', message='Format: 09123123123')])),
                ('email', models.EmailField(max_length=254)),
                ('facebookName', models.CharField(blank=True, default='', max_length=120)),
                ('address', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.CharField(choices=[('07:00:00', '07:00 AM'), ('08:00:00', '08:00 AM'), ('09:00:00', '09:00 AM'), ('10:00:00', '10:00 AM'), ('11:00:00', '11:00 AM'), ('12:00:00', '12:00 PM'), ('13:00:00', '01:00 PM'), ('14:00:00', '02:00 PM'), ('15:00:00', '03:00 PM'), ('16:00:00', '04:00 PM')], default='07:00 AM', max_length=8)),
                ('followup', models.BooleanField(default=False)),
                ('referralDoctor', models.CharField(blank=True, max_length=120, null=True)),
                ('newPatient', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('appointmentNumber', models.CharField(editable=False, max_length=14)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='backend.patient')),
            ],
        ),
    ]
