# Generated by Django 5.0.3 on 2024-03-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_patient_hospitalnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('07:00:00', '07:00 AM'), ('08:00:00', '08:00 AM'), ('09:00:00', '09:00 AM'), ('10:00:00', '10:00 AM'), ('11:00:00', '11:00 AM'), ('12:00:00', '12:00 PM'), ('13:00:00', '01:00 PM'), ('14:00:00', '02:00 PM'), ('15:00:00', '03:00 PM'), ('16:00:00', '04:00 PM')], default='07:00:00', max_length=8),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
