# Generated by Django 5.0.2 on 2024-03-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_appointment_id_alter_appointment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='facebookName',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
