# Generated by Django 5.0.3 on 2024-03-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFirst', models.CharField(max_length=120)),
                ('nameMiddle', models.CharField(max_length=120)),
                ('nameLast', models.CharField(max_length=120)),
                ('birthdate', models.DateField()),
                ('contact', models.IntegerField(max_length=11)),
            ],
        ),
    ]
