# Generated by Django 5.0.3 on 2024-03-13 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contact',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('^\\d{1,11}$')]),
        ),
    ]
