# Generated by Django 5.0.2 on 2024-03-25 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('specialization', models.CharField(max_length=120)),
                ('contact', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,11}$', message='Format: 09123123123')])),
                ('email', models.EmailField(max_length=254)),
                ('facebookName', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
