# Generated by Django 5.0.3 on 2024-03-14 03:39

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_patient_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='description',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='title',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointmentNumber',
            field=models.CharField(default='01012024-000', editable=False, max_length=12),
        ),
        migrations.AddField(
            model_name='appointment',
            name='followup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='newPatient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='backend.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='referral',
            field=models.ImageField(null=True, upload_to='referralImages/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[(datetime.time(9, 0), '09:00 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(13, 0), '01:00 PM'), (datetime.time(14, 0), '02:00 PM'), (datetime.time(15, 0), '03:00 PM'), (datetime.time(16, 0), '04:00 PM'), (datetime.time(17, 0), '05:00 PM'), (datetime.time(18, 0), '06:00 PM')], default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='hospitalNumber',
            field=models.CharField(default=0, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,11}$')]),
        ),
    ]
