# Generated by Django 5.0.2 on 2024-03-26 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
