# Generated by Django 5.0.3 on 2024-03-15 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_appointment_appointmentnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='newPatient',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentNumber',
            field=models.CharField(editable=False, max_length=12),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='referral',
            field=models.ImageField(blank=True, null=True, upload_to='referralImages/'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('07:00:00', '07:00 AM'), ('08:00:00', '08:00 AM'), ('09:00:00', '09:00 AM'), ('10:00:00', '10:00 AM'), ('11:00:00', '11:00 AM'), ('12:00:00', '12:00 PM'), ('13:00:00', '01:00 PM'), ('14:00:00', '02:00 PM'), ('15:00:00', '03:00 PM'), ('16:00:00', '04:00 PM')], default='09:00 AM', max_length=8),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,11}$', message='Format: 09123123123')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospitalNumber',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
