# Generated by Django 5.0.3 on 2024-03-15 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_appointment_newpatient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='referral',
        ),
        migrations.AddField(
            model_name='appointment',
            name='newPatient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='referralDoctor',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='civilStatus',
            field=models.CharField(choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED'), ('WIDOWED', 'WIDOWED'), ('SEPARATED', 'SEPARATED')], default='SINGLE', max_length=9),
        ),
        migrations.AddField(
            model_name='patient',
            name='facebookName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=6),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentNumber',
            field=models.CharField(editable=False, max_length=14),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('07:00:00', '07:00 AM'), ('08:00:00', '08:00 AM'), ('09:00:00', '09:00 AM'), ('10:00:00', '10:00 AM'), ('11:00:00', '11:00 AM'), ('12:00:00', '12:00 PM'), ('13:00:00', '01:00 PM'), ('14:00:00', '02:00 PM'), ('15:00:00', '03:00 PM'), ('16:00:00', '04:00 PM')], default='07:00 AM', max_length=8),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospitalNumber',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', message='Format: 123456')]),
        ),
    ]
