# Generated by Django 5.0.2 on 2024-03-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_appointment_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nameMiddle',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
