# Generated by Django 5.0.2 on 2024-03-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_patient_namemiddle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentNumber',
            field=models.CharField(editable=False, max_length=16),
        ),
    ]
