# Generated by Django 5.0.3 on 2024-03-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_appointment_referral_appointment_newpatient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
