# Generated by Django 5.0.2 on 2024-03-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nameFirst',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nameLast',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
