# Generated by Django 5.0.2 on 2024-04-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_appointment_appointmentnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='month',
            field=models.PositiveIntegerField(choices=[(1, 'JANUARY'), (2, 'FEBRUARY'), (3, 'MARCH'), (4, 'APRIL'), (5, 'MAY'), (6, 'JUNE'), (7, 'JULY'), (8, 'AUGUST'), (9, 'SEPTEMBER'), (10, 'OCTOBER'), (11, 'NOVEMBER'), (12, 'DECEMBER')], default=4),
        ),
    ]
