# Generated by Django 5.0.2 on 2024-03-17 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_patient_namefirst_alter_patient_namelast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact',
            field=models.CharField(blank=True, default=1, max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,11}$', message='Format: 09123123123')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='facebookName',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospitalNumber',
            field=models.CharField(blank=True, default=2, max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', message='Format: 123456')]),
            preserve_default=False,
        ),
    ]
