# Generated by Django 5.0.2 on 2024-04-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_setting_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='isPending',
            field=models.BooleanField(default=False),
        ),
    ]
